version: '3.8'

services:
  telemetry-service:
    build: .
    container_name: telemetry-service
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: http://influxdb:8086
      DATABASE_TOKEN: F-QFQpmCL9UkR3qyoXnLkzWj03s6m4eCvYgDl1ePfHBf9ph7yxaSgQ6WN0i9giNgRTfONwVMK1f977r_g71oNQ==
      DATABASE_ORG: smarthome
      DATABASE_BUCKET: telemetry
      SERVER_PORT: 8081
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: smarthome
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: F-QFQpmCL9UkR3qyoXnLkzWj03s6m4eCvYgDl1ePfHBf9ph7yxaSgQ6WN0i9giNgRTfONwVMK1f977r_g71oNQ==
    ports:
      - "8086:8086"