openapi: 3.0.0
info:
  title: telemetry-api
  version: 0.1.0
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Код ошибки
        message:
          type: string
          description: Сообщение об ошибке
    CurrentState:
      required:
        - device_id
        - temperature
        - timestamp
      properties:
        device_id:
          type: integer
          description: ID девайса
        temperature:
          type: integer
          description: Температура
        timestamp:
          type: integer
          description: Таймстамп замера

paths:
  /telemetry:
    post:
      description: Запись новых данных телеметрии
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CurrentState"
      responses:
        201:
          description: OK
        400:
          description: Невалидный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Ошибка при выполнении запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /telemetry/{device_id}/latest:
    get:
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      description: Получение текущего состояния девайса
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrentState"
        400:
          description: Невалидный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Не найден девайс
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Ошибка при выполнении запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"