// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Error defines model for Error.
type Error struct {
	// Code Код ошибки
	Code string `json:"code"`

	// Message Сообщение об ошибке
	Message string `json:"message"`
}

// HeatingStatus defines model for HeatingStatus.
type HeatingStatus struct {
	// DeviceId ID девайса
	DeviceId int `json:"device_id"`

	// Status Отопление включено (on/off)
	Status string `json:"status"`

	// UpdatedAt Дата и время обновления настройки
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// UpdatedBy Пользователь, который установил настройку
	UpdatedBy *int `json:"updated_by,omitempty"`
}

// HeatingStatusChange defines model for HeatingStatusChange.
type HeatingStatusChange struct {
	// Status Отопление включено (on/off)
	Status string `json:"status"`
}

// SetupDevice defines model for SetupDevice.
type SetupDevice struct {
	// DeviceId ID девайса
	DeviceId int `json:"device_id"`
}

// PostDevicesJSONRequestBody defines body for PostDevices for application/json ContentType.
type PostDevicesJSONRequestBody = SetupDevice

// PutDevicesDeviceIdStatusJSONRequestBody defines body for PutDevicesDeviceIdStatus for application/json ContentType.
type PutDevicesDeviceIdStatusJSONRequestBody = HeatingStatusChange

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /devices)
	PostDevices(w http.ResponseWriter, r *http.Request)

	// (GET /devices/{device_id}/status)
	GetDevicesDeviceIdStatus(w http.ResponseWriter, r *http.Request, deviceId int)

	// (PUT /devices/{device_id}/status)
	PutDevicesDeviceIdStatus(w http.ResponseWriter, r *http.Request, deviceId int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /devices)
func (_ Unimplemented) PostDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /devices/{device_id}/status)
func (_ Unimplemented) GetDevicesDeviceIdStatus(w http.ResponseWriter, r *http.Request, deviceId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /devices/{device_id}/status)
func (_ Unimplemented) PutDevicesDeviceIdStatus(w http.ResponseWriter, r *http.Request, deviceId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDevices operation middleware
func (siw *ServerInterfaceWrapper) PostDevices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevicesDeviceIdStatus operation middleware
func (siw *ServerInterfaceWrapper) GetDevicesDeviceIdStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevicesDeviceIdStatus(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDevicesDeviceIdStatus operation middleware
func (siw *ServerInterfaceWrapper) PutDevicesDeviceIdStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDevicesDeviceIdStatus(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices", wrapper.PostDevices)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}/status", wrapper.GetDevicesDeviceIdStatus)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/devices/{device_id}/status", wrapper.PutDevicesDeviceIdStatus)
	})

	return r
}

type PostDevicesRequestObject struct {
	Body *PostDevicesJSONRequestBody
}

type PostDevicesResponseObject interface {
	VisitPostDevicesResponse(w http.ResponseWriter) error
}

type PostDevices201Response struct {
}

func (response PostDevices201Response) VisitPostDevicesResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PostDevices400JSONResponse Error

func (response PostDevices400JSONResponse) VisitPostDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostDevices500JSONResponse Error

func (response PostDevices500JSONResponse) VisitPostDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesDeviceIdStatusRequestObject struct {
	DeviceId int `json:"device_id"`
}

type GetDevicesDeviceIdStatusResponseObject interface {
	VisitGetDevicesDeviceIdStatusResponse(w http.ResponseWriter) error
}

type GetDevicesDeviceIdStatus200JSONResponse HeatingStatus

func (response GetDevicesDeviceIdStatus200JSONResponse) VisitGetDevicesDeviceIdStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesDeviceIdStatus400JSONResponse Error

func (response GetDevicesDeviceIdStatus400JSONResponse) VisitGetDevicesDeviceIdStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesDeviceIdStatus404JSONResponse Error

func (response GetDevicesDeviceIdStatus404JSONResponse) VisitGetDevicesDeviceIdStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesDeviceIdStatus500JSONResponse Error

func (response GetDevicesDeviceIdStatus500JSONResponse) VisitGetDevicesDeviceIdStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutDevicesDeviceIdStatusRequestObject struct {
	DeviceId int `json:"device_id"`
	Body     *PutDevicesDeviceIdStatusJSONRequestBody
}

type PutDevicesDeviceIdStatusResponseObject interface {
	VisitPutDevicesDeviceIdStatusResponse(w http.ResponseWriter) error
}

type PutDevicesDeviceIdStatus204Response struct {
}

func (response PutDevicesDeviceIdStatus204Response) VisitPutDevicesDeviceIdStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutDevicesDeviceIdStatus400JSONResponse Error

func (response PutDevicesDeviceIdStatus400JSONResponse) VisitPutDevicesDeviceIdStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutDevicesDeviceIdStatus404JSONResponse Error

func (response PutDevicesDeviceIdStatus404JSONResponse) VisitPutDevicesDeviceIdStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutDevicesDeviceIdStatus500JSONResponse Error

func (response PutDevicesDeviceIdStatus500JSONResponse) VisitPutDevicesDeviceIdStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /devices)
	PostDevices(ctx context.Context, request PostDevicesRequestObject) (PostDevicesResponseObject, error)

	// (GET /devices/{device_id}/status)
	GetDevicesDeviceIdStatus(ctx context.Context, request GetDevicesDeviceIdStatusRequestObject) (GetDevicesDeviceIdStatusResponseObject, error)

	// (PUT /devices/{device_id}/status)
	PutDevicesDeviceIdStatus(ctx context.Context, request PutDevicesDeviceIdStatusRequestObject) (PutDevicesDeviceIdStatusResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostDevices operation middleware
func (sh *strictHandler) PostDevices(w http.ResponseWriter, r *http.Request) {
	var request PostDevicesRequestObject

	var body PostDevicesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostDevices(ctx, request.(PostDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostDevicesResponseObject); ok {
		if err := validResponse.VisitPostDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevicesDeviceIdStatus operation middleware
func (sh *strictHandler) GetDevicesDeviceIdStatus(w http.ResponseWriter, r *http.Request, deviceId int) {
	var request GetDevicesDeviceIdStatusRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevicesDeviceIdStatus(ctx, request.(GetDevicesDeviceIdStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevicesDeviceIdStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevicesDeviceIdStatusResponseObject); ok {
		if err := validResponse.VisitGetDevicesDeviceIdStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutDevicesDeviceIdStatus operation middleware
func (sh *strictHandler) PutDevicesDeviceIdStatus(w http.ResponseWriter, r *http.Request, deviceId int) {
	var request PutDevicesDeviceIdStatusRequestObject

	request.DeviceId = deviceId

	var body PutDevicesDeviceIdStatusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutDevicesDeviceIdStatus(ctx, request.(PutDevicesDeviceIdStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDevicesDeviceIdStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutDevicesDeviceIdStatusResponseObject); ok {
		if err := validResponse.VisitPutDevicesDeviceIdStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xVzWrbShR+FTH3Lu4FxVLudTdatilt6KKBLEMIqjV2VGJJnRkHghEkDvSHlAZKV4Wm",
	"7RsoTkTkuFZe4cwblTOSLdtSShZumkJXGs0w53znnO/7pksafjvwPeoJTqwu4Y1t2rbV8iFjPsNFwPyA",
	"MuFStd3wHYpfh/IGcwPh+h6xCHyEFM41SOVrSOAULiEhOhF7ASUW4YK5XouEOmlTzu1W1f2vkEIKp/IN",
	"xDCCBGINf6cDxuWAoU4YfdFxGXWItZFBK5Jshjp5TG3heq11YYsOLxfj0F23Qbdcp4xodUWDc4ihDxEM",
	"5AFERXrXE7RFGRbEJ4Hn6jmRPUjhCoZFPX24hKF8J1+prVT7x/cMv9n8t6pRncCxBXW2bFER+wNEsgeR",
	"BokGfbkPMXyTx6pfGBf646S4OYJIHsie3IcUBvlYmj5rY2CCOZaE26Y/gvBsrwLCZ0hhKN/ChcqHcGL8",
	"1zW4hBRLl/vyCAaaPMTsEOXAEhiWIMnDis7OTbaY06Tlpek+2La9jFqzM/45I5oDOAVqnYpOsKIAL5xw",
	"17ZlM8Qz12v6GFi4YgfvZed8yQ5copNdyniWyqwt10ycsR9QDw8t8n/NrJlEJ4EtthVSI7+savB5FQ+/",
	"QAxnkOTDjOTLMeVw1CmcQVquCJthY4BVh1hkzediJc+TlUa5uO87e5nTeIJ6KrEdBDtuQ90znnPMPrYq",
	"XP3NaJNY5C+j8DIjNzJjehphmDWQB77Hs8r+M5fLhT19gr2pm+bCUGReqtLP9fBT3p8hJHAOIyUauIAI",
	"rlAf8gCR3LsVJCcTp400lV25yxFcodRhlIskmUEHUd7UMVuM7oSToVEor0XFtSZymKsNBZiZheyhbSCM",
	"WT0qdqWzqpXHJVI9omNOZZ9VJ7d/ZDez21RQxom10SUuwkDGE514druQTOY0hdQE61B9qsMlXW6WeLW4",
	"kc2+YRWju2t8rZv120Gi3hIYKJMZzXjN7yAbnQSdKlm8nyU9xIYi/dzmTZSw1vlFSli8j1c99ZV+Xr/7",
	"fv5HHzd7VsLwewAAAP//4lEUIp8MAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
