@startuml
title SmartHome SettingsService Code Diagram

top to bottom direction

!include C4_Component.puml

class Settings {
    +Int deviceID
    +Int temperature
    +Bool isHeatingOn
    +Int changedByUserID
    +Date updatedAt
}

class TemperatureChange {
    +Int userID
    +TemperatureSettings settings
}

class HeatingChange {
    +Bool isOn
    +HeatingSettings settings
}

class HeatingSettings {
   +Int deviceID
   +Bool isOn
}

class TemperatureSettings {
    +Int temperature
    +Int device ID
}

class TemperatureService {
    Repository repository
    +void updateTemperature(temperature TemperatureChange)
    +TemperatureSettings getTemperatureSettings(deviceID Int)
}

class HeatingService {
    Repository repository
    +void updateHeating(change HeatingChange)
    +HeatingSettings getHeatingSettings(deviceID Int)
}

class Repository {
    +void updateHeating(change HeatingChange)
    +void updateTemperature(temperature TemperatureChange)
    +Settings getSettings(deviceID Int)
    +HeatingSettings getHeatingSettings(deviceID Int)
    +TemperatureSettings getTemperatureSettings(deviceID Int)
}

HeatingService "1" -- "1" Repository : includes
TemperatureService "1" -- "1" Repository : includes
HeatingChange "1" -- "1" HeatingSettings : includes
TemperatureChange "1" -- "1" TemperatureSettings : includes


@enduml
